language: java
jdk:
  - openjdk15
before_install:
  - mvn install:install-file -Dfile=lib/sikulixsetup-1.1.0.jar -DgroupId=org.sikuli -DartifactId=sikuli-setup -Dversion=1.1.0 -Dpackaging=jar -DgeneratePom=true
  - mvn install:install-file -Dfile=lib/sikulixapi.jar -DgroupId=org.sikuli -DartifactId=sikuli-api -Dversion=1.2.0 -Dpackaging=jar -DgeneratePom=true
